packages:
  - .

allowBuilds:
  esbuild: false
  protobufjs: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - ip-address@10.1.1

overrides:
  compromise: 14.14.4
  eslint-import-resolver-typescript: '^4.4.4'
  semver: '>=7'
  ip-address@<=10.1.0: ^10.1.1

strictPeerDependencies: false

trustPolicy: no-downgrade
